name: test_udemy_firebase
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:

  algolia: ^1.1.1
  clipboard: ^0.1.3
  cloud_firestore: ^4.1.0
  cupertino_icons: ^1.0.2

  firebase_analytics: ^10.0.6
  firebase_auth: ^4.1.3
  firebase_core: ^2.3.0
  firebase_crashlytics: ^3.0.6
  firebase_storage: ^11.0.6
  flash: ^2.0.5
  flutter:
    sdk: flutter

  flutter_dotenv: ^5.0.2
  flutter_launcher_icons: ^0.11.0
  flutter_riverpod: ^2.1.1
  flutter_svg: ^1.1.6
  fluttertoast: ^8.1.1
  google_fonts: ^3.0.1
  http: ^0.13.5
  image_cropper: ^3.0.1
  image_picker: ^0.8.6
  intl: ^0.17.0
  material_floating_search_bar: ^0.3.7
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.7
  uuid: ^3.0.7

dev_dependencies:

  build_runner: ^2.3.2
  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter
  freezed: ^2.2.1
  freezed_annotation: ^2.2.0
  json_serializable: ^6.5.4
  
flutter:

  uses-material-design: true
