// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, no_default_cases
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVP816_YOtBtCfCIxOMl6QcnpLrisJnUQ',
    appId: '1:544704950517:android:6bbae0b532f93908e395bc',
    messagingSenderId: '544704950517',
    projectId: 'flutter-firebase-1123',
    storageBucket: 'flutter-firebase-1123.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFlOO45fmIIit5O0ogVWNNgHloJzXi2MQ',
    appId: '1:544704950517:ios:812e4ad8e3116e32e395bc',
    messagingSenderId: '544704950517',
    projectId: 'flutter-firebase-1123',
    storageBucket: 'flutter-firebase-1123.appspot.com',
    iosClientId:
        '544704950517-nknbqg96fjl795f2kbd0l92t1jg6n91b.apps.googleusercontent.com',
    iosBundleId: 'com.example.testUdemyFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFlOO45fmIIit5O0ogVWNNgHloJzXi2MQ',
    appId: '1:544704950517:ios:812e4ad8e3116e32e395bc',
    messagingSenderId: '544704950517',
    projectId: 'flutter-firebase-1123',
    storageBucket: 'flutter-firebase-1123.appspot.com',
    iosClientId:
        '544704950517-nknbqg96fjl795f2kbd0l92t1jg6n91b.apps.googleusercontent.com',
    iosBundleId: 'com.example.testUdemyFirebase',
  );
}
